name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Go proxy credentials
        run: |
          cat >> ~/.netrc <<EOF
          machine goproxy.pazer.io login ${{ secrets.GOPROXY_USER }} password ${{ secrets.GOPROXY_PASSWORD }}
          EOF
          chmod 600 ~/.netrc

      - name: Go Toolchain
        uses: wow-look-at-my/go-toolchain@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GO_BUILDCACHE_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GO_BUILDCACHE_ACCESS_KEY }}
          GOCACHE_S3_ENDPOINT: ${{ secrets.GO_BUILDCACHE_ENDPOINT }}
          GOCACHE_S3_REGION: ${{ secrets.GO_BUILDCACHE_REGION }}
